apiVersion: v1
kind: Service
metadata:
  name: to-do-app-service
  labels:
    app: to-do-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: to-do-app
  ports:
    - protocol: TCP
      port: 80        # external port (LB receives this)
      targetPort: 80  # container port
  type: LoadBalancer   # ✅ AWS will provision an ELB automatically
