apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - port: 80  # service port
      targetPort: 80 # pod containerPort
      nodePort: 30080   # Must match Terraform ALB target group
