apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: to-do-app
  namespace: argocd   # ArgoCD itself runs in 'argocd' namespace
spec:
  project: default

  source:
    repoURL: 'https://github.com/UdayParkar/to-do-app.git'
    targetRevision: main
    path: k8s   # ✅ must match your repo folder
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
