apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd   # ArgoCD itself runs in the argocd namespace
spec:
  project: default

  source:
    repoURL: 'https://github.com/UdayParkar/to-do-app.git'   # 👈 your repo
    targetRevision: main                                    # branch to track
    path: k8s                                               # folder where yamls live

  destination:
    server: https://kubernetes.default.svc
    namespace: default   # or use "todo-app" if you want isolation

  syncPolicy:
    automated:       # 👈 enables GitOps auto-sync
      prune: true    # delete resources not in Git
      selfHeal: true # re-apply if drift happens
    syncOptions:
      - CreateNamespace=true
